# Generated by Django 6.0.3 on 2026-03-24 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('family', models.CharField(blank=True, max_length=100)),
                ('economic_importance', models.TextField(blank=True)),
                ('growing_regions', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('disease_type', models.CharField(choices=[('fungal', 'Fungal Disease'), ('bacterial', 'Bacterial Disease'), ('viral', 'Viral Disease'), ('other', 'Other')], default='fungal', max_length=20)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('about', models.TextField(help_text='About the disease')),
                ('identification', models.TextField(help_text='How to identify the disease')),
                ('symptoms', models.TextField(help_text='Symptoms of infestation')),
                ('management', models.TextField(help_text='Management measures')),
                ('disease_cycle', models.TextField(blank=True)),
                ('favorable_conditions', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diseases/')),
            ],
            options={
                'verbose_name_plural': 'Diseases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EconomicImportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='economic_importance/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('effects', models.TextField()),
                ('management', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='environmental_factors/')),
            ],
        ),
        migrations.CreateModel(
            name='IdentificationImportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='identification_importance/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IPMPrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NutrientDeficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('deficiency_type', models.CharField(choices=[('N', 'Nitrogen'), ('P', 'Phosphorus'), ('K', 'Potassium'), ('Mg', 'Magnesium'), ('Ca', 'Calcium'), ('Fe', 'Iron'), ('Zn', 'Zinc'), ('Other', 'Other')], max_length=10)),
                ('symptoms', models.TextField()),
                ('causes', models.TextField()),
                ('management', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='nutrient_deficiencies/')),
            ],
        ),
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pest_type', models.CharField(choices=[('insect', 'Insect Pest'), ('mite', 'Mite'), ('nematode', 'Nematode'), ('vertebrate', 'Vertebrate Pest'), ('other', 'Other')], default='insect', max_length=20)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('about', models.TextField(help_text='About the pest')),
                ('identification', models.TextField(help_text='How to identify the pest')),
                ('symptoms', models.TextField(help_text='Symptoms of infestation')),
                ('management', models.TextField(help_text='Management measures')),
                ('lifecycle', models.TextField(blank=True)),
                ('host_range', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pests/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Pest Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PesticideUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('best_practices', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diseases/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.disease')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ControlMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('method_type', models.CharField(choices=[('cultural', 'Cultural Control'), ('biological', 'Biological Control'), ('mechanical', 'Mechanical Control'), ('chemical', 'Chemical Control'), ('integrated', 'Integrated Control')], max_length=20)),
                ('description', models.TextField()),
                ('application', models.TextField()),
                ('advantages', models.TextField(blank=True)),
                ('disadvantages', models.TextField(blank=True)),
                ('diseases', models.ManyToManyField(blank=True, related_name='control_methods', to='core.disease')),
                ('pests', models.ManyToManyField(blank=True, related_name='control_methods', to='core.pest')),
            ],
        ),
        migrations.CreateModel(
            name='VertebratePest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pest',),
        ),
        migrations.AddField(
            model_name='pest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pests', to='core.pestcategory'),
        ),
        migrations.AddField(
            model_name='disease',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diseases', to='core.pestcategory'),
        ),
        migrations.CreateModel(
            name='PestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pests/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.pest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CropDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Specific description for this crop-disease relationship')),
                ('damage_symptoms', models.TextField(blank=True, help_text='Damage/Symptoms specific to this crop')),
                ('management_measures', models.TextField(blank=True, help_text='Management measures specific to this crop')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_diseases', to='core.crop')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_diseases', to='core.disease')),
            ],
            options={
                'unique_together': {('crop', 'disease')},
            },
        ),
        migrations.CreateModel(
            name='CropPest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Specific description for this crop-pest relationship')),
                ('damage_symptoms', models.TextField(blank=True, help_text='Damage/Symptoms specific to this crop')),
                ('management_measures', models.TextField(blank=True, help_text='Management measures specific to this crop')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_pests', to='core.crop')),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_pests', to='core.pest')),
            ],
            options={
                'unique_together': {('crop', 'pest')},
            },
        ),
    ]
