# Generated by Django 6.0.3 on 2026-04-02 12:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('invertebrate-pests', 'Invertebrate Pests'), ('diseases', 'Plant Diseases'), ('vertebrate-pests', 'Vertebrate Pests'), ('abiotic', 'Abiotic Causes'), ('invasive-alien', 'Invasive Alien Species'), ('post-harvest', 'Post-Harvest Damage'), ('weeds', 'Weed Competition')], db_index=True, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color_code', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Classification Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('area_km2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(choices=[('cereal', 'Cereal'), ('legume', 'Legume'), ('vegetable', 'Vegetable'), ('tuber', 'Tuber/Root Crop'), ('fruit', 'Fruit'), ('cash-crop', 'Cash Crop'), ('oil-crop', 'Oil Crop'), ('fiber', 'Fiber Crop')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('icon', models.CharField(blank=True, help_text='Emoji icon for display', max_length=10)),
                ('growing_season_start', models.CharField(blank=True, max_length=50)),
                ('growing_season_end', models.CharField(blank=True, max_length=50)),
                ('average_yield_kg_per_ha', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'category'], name='api_crop_name_11b460_idx'), models.Index(fields=['is_active'], name='api_crop_is_acti_e16b5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PestDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=300, null=True)),
                ('local_names', models.CharField(blank=True, help_text='Comma-separated local names', max_length=500)),
                ('issue_type', models.CharField(choices=[('insect', 'Insect Pest'), ('mite', 'Mite'), ('nematode', 'Nematode'), ('fungal', 'Fungal Disease'), ('bacterial', 'Bacterial Disease'), ('viral', 'Viral Disease'), ('vertebrate', 'Vertebrate Pest'), ('abiotic', 'Abiotic Stress'), ('weed', 'Weed'), ('invasive', 'Invasive Species'), ('post-harvest', 'Post-Harvest Issue')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=20)),
                ('damage_type', models.CharField(choices=[('direct', 'Direct Damage'), ('indirect', 'Indirect Damage'), ('both', 'Both Direct and Indirect')], default='direct', max_length=20)),
                ('description', models.TextField()),
                ('symptoms', models.TextField(help_text='Detailed symptoms with bullet points')),
                ('control_methods', models.TextField(help_text='Control methods (cultural, biological, chemical)')),
                ('prevention_methods', models.TextField(help_text='Prevention strategies')),
                ('economic_impact', models.TextField(blank=True, help_text='Economic impact description')),
                ('yield_loss_percentage_min', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('yield_loss_percentage_max', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('distribution_kenya', models.TextField(help_text='Distribution across Kenyan counties/regions')),
                ('global_distribution', models.TextField(blank=True)),
                ('seasonal_pattern', models.CharField(blank=True, help_text='When is this issue most prevalent', max_length=500)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='pests_diseases/')),
                ('symptom_image', models.ImageField(blank=True, null=True, upload_to='pests_diseases/symptoms/')),
                ('damage_image', models.ImageField(blank=True, null=True, upload_to='pests_diseases/damage/')),
                ('life_cycle_days', models.IntegerField(blank=True, help_text='Average life cycle in days', null=True)),
                ('is_vector', models.BooleanField(default=False, help_text='Does this pest transmit diseases?')),
                ('vector_for', models.TextField(blank=True, help_text='What diseases does it transmit?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_emerging', models.BooleanField(default=False, help_text='Is this an emerging threat?')),
                ('affects_crops', models.ManyToManyField(blank=True, related_name='pests_diseases', to='api.crop')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.classificationcategory')),
            ],
            options={
                'verbose_name_plural': 'Pests and Diseases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OutbreakReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, help_text='Specific location/ward', max_length=300)),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('severe', 'Severe')], max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('confirmed', 'Confirmed'), ('contained', 'Contained'), ('ongoing', 'Ongoing'), ('resolved', 'Resolved')], default='reported', max_length=20)),
                ('affected_area_ha', models.FloatField(blank=True, help_text='Affected area in hectares', null=True)),
                ('estimated_loss', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated loss in KES', max_digits=12, null=True)),
                ('reporter_name', models.CharField(blank=True, max_length=200)),
                ('reporter_contact', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbreaks', to='api.county')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to=settings.AUTH_USER_MODEL)),
                ('pest_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbreaks', to='api.pestdisease')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='ManagementPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('cultural', 'Cultural Practice'), ('biological', 'Biological Control'), ('chemical', 'Chemical Control'), ('physical', 'Physical Control'), ('integrated', 'Integrated Pest Management'), ('preventive', 'Preventive Measure')], max_length=50)),
                ('description', models.TextField()),
                ('application_method', models.CharField(blank=True, max_length=500)),
                ('timing', models.CharField(help_text='When to apply this practice', max_length=500)),
                ('frequency', models.CharField(blank=True, help_text='How often to apply', max_length=200)),
                ('effectiveness_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('estimated_cost_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_per_unit', models.CharField(blank=True, help_text='e.g., per acre, per hectare', max_length=100)),
                ('safety_precautions', models.TextField(blank=True)),
                ('reentry_interval_days', models.IntegerField(blank=True, help_text='Days before re-entry after application', null=True)),
                ('is_organic', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crops', models.ManyToManyField(blank=True, related_name='management_practices', to='api.crop')),
                ('targets', models.ManyToManyField(blank=True, related_name='management_practices', to='api.pestdisease')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('inaccurate', 'Inaccurate'), ('outdated', 'Outdated'), ('suggestion', 'Suggestion')], max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('user_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL)),
                ('pest_disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.pestdisease')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EarlyWarningAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('alert_level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_actions', models.TextField()),
                ('source', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('affected_counties', models.ManyToManyField(blank=True, related_name='alerts', to='api.county')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pest_disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.pestdisease')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='PestDiseaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('adult', 'Adult Stage'), ('larva', 'Larva/Nymph'), ('egg', 'Egg Stage'), ('symptom', 'Symptom'), ('damage', 'Damage'), ('control', 'Control Method')], max_length=50)),
                ('image', models.ImageField(upload_to='pests_diseases/additional/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('pest_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='api.pestdisease')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video Tutorial'), ('article', 'Article'), ('infographic', 'Infographic'), ('tool', 'Interactive Tool')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resources/thumbnails/')),
                ('duration', models.CharField(blank=True, help_text="For videos: e.g., '10:30'", max_length=50)),
                ('file_size', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(default='English', max_length=50)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_crops', models.ManyToManyField(blank=True, related_name='resources', to='api.crop')),
                ('related_pests_diseases', models.ManyToManyField(blank=True, related_name='resources', to='api.pestdisease')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('search_query', models.CharField(max_length=500)),
                ('search_filters', models.JSONField(default=dict, help_text='Stores search filters as JSON')),
                ('results_count', models.IntegerField(default=0)),
                ('clicked_result', models.CharField(blank=True, max_length=300, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_alerts', models.BooleanField(default=True)),
                ('alert_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='daily', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_counties', models.ManyToManyField(blank=True, related_name='favorite_of', to='api.county')),
                ('favorite_crops', models.ManyToManyField(blank=True, related_name='favorite_of', to='api.crop')),
                ('saved_management_practices', models.ManyToManyField(blank=True, related_name='saved_by', to='api.managementpractice')),
                ('saved_pests_diseases', models.ManyToManyField(blank=True, related_name='saved_by', to='api.pestdisease')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='pestdisease',
            index=models.Index(fields=['name', 'severity'], name='api_pestdis_name_7d5b09_idx'),
        ),
        migrations.AddIndex(
            model_name='pestdisease',
            index=models.Index(fields=['issue_type', 'category'], name='api_pestdis_issue_t_3bde5f_idx'),
        ),
        migrations.AddIndex(
            model_name='pestdisease',
            index=models.Index(fields=['is_active', 'is_emerging'], name='api_pestdis_is_acti_bacca9_idx'),
        ),
        migrations.AddIndex(
            model_name='outbreakreport',
            index=models.Index(fields=['pest_disease', 'county'], name='api_outbrea_pest_di_4f8c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='outbreakreport',
            index=models.Index(fields=['report_date', 'severity'], name='api_outbrea_report__b7b6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='earlywarningalert',
            index=models.Index(fields=['alert_level', 'is_active'], name='api_earlywa_alert_l_e224d6_idx'),
        ),
        migrations.AddIndex(
            model_name='earlywarningalert',
            index=models.Index(fields=['start_date', 'end_date'], name='api_earlywa_start_d_099c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', 'created_at'], name='api_searchh_user_id_62d48d_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['session_id', 'created_at'], name='api_searchh_session_5473d4_idx'),
        ),
    ]
